language: r

cache: packages

sudo: false

r_packages:
  - devtools
  - roxygen2
  - Rcpp

before_install:
  - Rscript -e 'Rcpp::compileAttributes()'
  - Rscript -e 'install.packages(c("devtools","roxygen2"));devtools::document()'

r_build_args: --no-build-vignettes --no-manual --no-resave-data
r_check_args: --no-build-vignettes --no-manual