language: r

cache: packages

sudo: false

r_packages:
  - devtools
  - roxygen2
  - Rcpp

before_install:
  - Rscript -e 'install.packages("roxygen2"); roxygen2::roxygenize()'
  - Rscript -e 'Rcpp::compileAttributes()'

r_build_args: --no-build-vignettes --no-manual --no-resave-data
r_check_args: --no-build-vignettes --no-manual