# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

glmLasso <- function(X, y, o, lambda, family, KLB, thresh, maxIter, threads) {
    .Call('MixedGraphs_glmLasso', PACKAGE = 'MixedGraphs', X, y, o, lambda, family, KLB, thresh, maxIter, threads)
}

glmRidge <- function(X, y, o, lambda, family, thresh, maxIter) {
    .Call('MixedGraphs_glmRidge', PACKAGE = 'MixedGraphs', X, y, o, lambda, family, thresh, maxIter)
}

test <- function(X, y, method = "Gaussian", lambda = 0.5) {
    .Call('MixedGraphs_test', PACKAGE = 'MixedGraphs', X, y, method, lambda)
}

testADMM <- function(X, y, method = "Gaussian", lambda = 0.5) {
    .Call('MixedGraphs_testADMM', PACKAGE = 'MixedGraphs', X, y, method, lambda)
}

testNewton <- function(X, y, method = "Gaussian", lambda = 0.5) {
    .Call('MixedGraphs_testNewton', PACKAGE = 'MixedGraphs', X, y, method, lambda)
}

testBRAIL <- function(X, y, method = "gaussian") {
    .Call('MixedGraphs_testBRAIL', PACKAGE = 'MixedGraphs', X, y, method)
}

