# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test <- function(X, y, method = "Gaussian", lambda = 0.5) {
    .Call('MixedGraphs_test', PACKAGE = 'MixedGraphs', X, y, method, lambda)
}

testADMM <- function(X, y, method = "Gaussian", lambda = 0.5) {
    .Call('MixedGraphs_testADMM', PACKAGE = 'MixedGraphs', X, y, method, lambda)
}

testNewton <- function(X, y, method = "Gaussian", lambda = 0.5) {
    .Call('MixedGraphs_testNewton', PACKAGE = 'MixedGraphs', X, y, method, lambda)
}

